from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Literal

import numpy as np

from .constants import G0
from .core import trapezoid_integrate
from .records import MotionRecord
from .units import acceleration_from_si, normalize_units


@dataclass(frozen=True, slots=True)
class GroundMotionParameters:
    pga: float
    pgv: float
    pgd: float
    arias_intensity: float
    d5_75: float
    d5_95: float
    cav: float
    rms_acceleration: float
    bracketed_duration: float
    final_velocity: float
    final_displacement: float


def integrate_motion(
    acceleration_si: np.ndarray, dt: float
) -> tuple[np.ndarray, np.ndarray]:
    velocity = trapezoid_integrate(
        np.asarray(acceleration_si, dtype=np.float64), float(dt), 0.0
    )
    displacement = trapezoid_integrate(velocity, float(dt), 0.0)
    return velocity, displacement


def cumulative_arias(acceleration_si: np.ndarray, dt: float) -> np.ndarray:
    acc = np.asarray(acceleration_si, dtype=np.float64)
    acc2 = acc * acc
    integral = trapezoid_integrate(acc2, float(dt), 0.0)
    return (np.pi / (2.0 * G0)) * integral


def _time_at_fraction(
    time: np.ndarray, cumulative: np.ndarray, fraction: float
) -> float:
    total = float(cumulative[-1])
    if total <= 0.0:
        return float(time[0])
    target = fraction * total
    idx = int(np.searchsorted(cumulative, target, side="left"))
    if idx <= 0:
        return float(time[0])
    if idx >= cumulative.size:
        return float(time[-1])
    x0 = cumulative[idx - 1]
    x1 = cumulative[idx]
    if x1 == x0:
        return float(time[idx])
    alpha = (target - x0) / (x1 - x0)
    return float(time[idx - 1] + alpha * (time[idx] - time[idx - 1]))


def significant_duration(
    time: np.ndarray, arias_curve: np.ndarray, start: float, end: float
) -> float:
    return _time_at_fraction(time, arias_curve, end) - _time_at_fraction(
        time, arias_curve, start
    )


def bracketed_duration(
    acceleration_si: np.ndarray, dt: float, threshold_g: float = 0.05
) -> float:
    mask = np.abs(acceleration_si) >= threshold_g * G0
    if not np.any(mask):
        return 0.0
    idx = np.flatnonzero(mask)
    return float((idx[-1] - idx[0]) * dt)


def _as_1d_float(values: np.ndarray, name: str) -> np.ndarray:
    arr = np.asarray(values, dtype=np.float64)
    if arr.ndim != 1:
        raise ValueError(f"{name} must be a one-dimensional array")
    if arr.size < 2:
        raise ValueError(f"{name} needs at least two samples")
    if not np.all(np.isfinite(arr)):
        raise ValueError(f"{name} values must be finite")
    return arr


def _check_same_length(reference: np.ndarray, values: np.ndarray, name: str) -> None:
    if values.size != reference.size:
        raise ValueError(f"{name} must have the same length as acceleration")


def compute_ground_motion_parameters_from_series(
    time: np.ndarray,
    acceleration_si: np.ndarray,
    *,
    velocity_si: np.ndarray | None = None,
    displacement_si: np.ndarray | None = None,
    threshold_g: float = 0.05,
) -> GroundMotionParameters:
    """Compute intensity measures from acceleration, velocity and displacement series.

    Inputs and outputs are in SI units:
    acceleration in m/s^2, velocity in m/s, displacement in m.

    If velocity and/or displacement are not supplied they are computed by trapezoidal
    integration from the acceleration. Supplying velocity_si and displacement_si is
    useful when comparing against reference channels where velocity/displacement were
    generated by an external correction procedure and are not the direct numerical
    integral of the provided acceleration channel.
    """

    t = _as_1d_float(time, "time")
    acc = _as_1d_float(acceleration_si, "acceleration_si")
    _check_same_length(acc, t, "time")
    diffs = np.diff(t)
    if np.any(diffs <= 0.0):
        raise ValueError("time must be strictly increasing")
    dt = float(np.median(diffs))
    atol = max(1.0e-12, abs(dt) * 1.0e-8)
    if not np.allclose(diffs, dt, rtol=1.0e-5, atol=atol):
        raise ValueError("time must be uniformly sampled")

    integrated_velocity, integrated_displacement = integrate_motion(acc, dt)

    if velocity_si is None:
        vel = integrated_velocity
    else:
        vel = _as_1d_float(velocity_si, "velocity_si")
        _check_same_length(acc, vel, "velocity_si")

    if displacement_si is None:
        disp = (
            integrated_displacement
            if velocity_si is None
            else trapezoid_integrate(vel, dt, 0.0)
        )
    else:
        disp = _as_1d_float(displacement_si, "displacement_si")
        _check_same_length(acc, disp, "displacement_si")

    arias = cumulative_arias(acc, dt)
    abs_acc = np.abs(acc)
    duration = float(t[-1] - t[0])
    cav = float(np.trapezoid(abs_acc, dx=dt))
    rms = float(np.sqrt(np.trapezoid(acc * acc, dx=dt) / max(duration, dt)))
    return GroundMotionParameters(
        pga=float(abs_acc.max()),
        pgv=float(np.abs(vel).max()),
        pgd=float(np.abs(disp).max()),
        arias_intensity=float(arias[-1]),
        d5_75=float(significant_duration(t, arias, 0.05, 0.75)),
        d5_95=float(significant_duration(t, arias, 0.05, 0.95)),
        cav=cav,
        rms_acceleration=rms,
        bracketed_duration=bracketed_duration(acc, dt, threshold_g=threshold_g),
        final_velocity=float(vel[-1]),
        final_displacement=float(disp[-1]),
    )


def compute_ground_motion_parameters(
    record: MotionRecord, *, threshold_g: float = 0.05
) -> GroundMotionParameters:
    return compute_ground_motion_parameters_from_series(
        record.time,
        record.acceleration_si(),
        threshold_g=threshold_g,
    )


def _velocity_from_si(values: float | np.ndarray, units: str) -> float | np.ndarray:
    unit = normalize_units(units)
    if unit == "m/s":
        return values
    if unit in {"cm/s", "cm/sec"}:
        return np.asarray(values) * 100.0
    raise ValueError(f"Unsupported velocity units: {units!r}")


def _displacement_from_si(values: float | np.ndarray, units: str) -> float | np.ndarray:
    unit = normalize_units(units)
    if unit == "m":
        return values
    if unit == "cm":
        return np.asarray(values) * 100.0
    if unit == "mm":
        return np.asarray(values) * 1000.0
    raise ValueError(f"Unsupported displacement units: {units!r}")


def ground_motion_parameters_to_dict(
    params: GroundMotionParameters,
    *,
    acceleration_units: Literal["m/s^2", "cm/s^2", "g"] = "m/s^2",
    velocity_units: Literal["m/s", "cm/s"] = "m/s",
    displacement_units: Literal["m", "cm", "mm"] = "m",
    cav_units: Literal["m/s", "cm/s"] = "m/s",
    suffix_units: bool = False,
) -> dict[str, float]:
    """Return ground-motion parameters in explicit display units.

    The GroundMotionParameters dataclass stores SI values. This helper is intended
    for tables and reports where the displayed units should match the plotted
    acceleration/velocity/displacement channels.
    """

    acc_unit = normalize_units(acceleration_units)
    vel_unit = normalize_units(velocity_units)
    disp_unit = normalize_units(displacement_units)
    cav_unit = normalize_units(cav_units)

    row = asdict(params)
    row["pga"] = float(acceleration_from_si(params.pga, acc_unit))
    row["rms_acceleration"] = float(
        acceleration_from_si(params.rms_acceleration, acc_unit)
    )
    row["pgv"] = float(_velocity_from_si(params.pgv, vel_unit))
    row["final_velocity"] = float(_velocity_from_si(params.final_velocity, vel_unit))
    row["pgd"] = float(_displacement_from_si(params.pgd, disp_unit))
    row["final_displacement"] = float(
        _displacement_from_si(params.final_displacement, disp_unit)
    )
    row["cav"] = float(_velocity_from_si(params.cav, cav_unit))

    if not suffix_units:
        return row

    return {
        f"pga_{acc_unit.replace('/', '_').replace('^', '')}": row["pga"],
        f"pgv_{vel_unit.replace('/', '_')}": row["pgv"],
        f"pgd_{disp_unit}": row["pgd"],
        "arias_intensity_m_s": row["arias_intensity"],
        "d5_75_s": row["d5_75"],
        "d5_95_s": row["d5_95"],
        f"cav_{cav_unit.replace('/', '_')}": row["cav"],
        f"rms_acceleration_{acc_unit.replace('/', '_').replace('^', '')}": row[
            "rms_acceleration"
        ],
        "bracketed_duration_s": row["bracketed_duration"],
        f"final_velocity_{vel_unit.replace('/', '_')}": row["final_velocity"],
        f"final_displacement_{disp_unit}": row["final_displacement"],
    }
